# Generated by Django 3.0.6 on 2020-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
